### ISSUE TITLE
Error fighting with mob

### ISSUE THREAD

**Issue by avalon666** [PaulAnthonyReitz/ReitzMMO#14] opened 2019-06-01 16:14 UTC
[Error](https://pastebin.com/Uj6kbYnw)

**Comment by avalon666** [comment] 2019-06-09 10:13
After updating Worldguard to 7.0.0-SNAPSHOT-dist#1903-426a709 the error was gone. Since the update of ReitzMMO to 1.16 the [bug](https://pastebin.com/dtdQw60v) is back.

**Comment by RitzDaCat** [comment] 2019-06-11 15:57
Believe this was caused by a JavaIllegalException where a mob did not have a name assigned or it had issues parsing the value. Believe I have this fixed in the next update.

**Comment by avalon666** [comment] 2019-07-19 19:02
Sorry, it's me again. ;-D
[Mob-Error](https://pastebin.com/B54hr3QA)

**Comment by RitzDaCat** [comment] 2020-01-05 00:21
This should be resolved in 1.20 with the new system as I got away from checking mob names.

**Closed as completed by RitzDaCat** 2020-01-05 00:21 UTC
Labels: bug
